### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by jubishop** [SudhagarS/pry-state#11]
hey there :) i've successfully gem installed pry-state, alas my pry sessions with a binding.pry don't show any variables like in the screenshot.  is this repo still working?  thanks for any help!

**Comment by SudhagarS** [comment]
@jubishop Oh. I will look into it asap and let you know.

**Comment by jubishop** [comment]
thanks SudhagarS.  I never did get the gem to work, but i reverse engineered a lot of your efforts into my own pryrc file to get similar functionality :) thanks for the source code!  https://github.com/jubishop/pryrc/blob/master/pryrc.rb
