### ISSUE TITLE
REQUEST: Complex object internal variables

### ISSUE THREAD

**Issue by ootoovak** [SudhagarS/pry-state#3]
Great gem so far btw :smile:, I like the variable output printed below the code! One request I have if you ever have the time to try it would be to have the objects output their internal values like [pry-inline](https://github.com/seikichi/pry-inline).

For example instead of:

``` ruby
#<Aws::S3::Bucket:0x007faec4a11043>
```

You would get:

``` ruby
#<Aws::S3::Bucket name="development-bucket">
```

**Comment by SudhagarS** [comment]
@ootoovak Thanks. pry-inline also looks promising. Will start the work on getting that kind of output. ✌️

**Comment by ootoovak** [comment]
Awesome great to hear. Thanks. :smile:

**Comment by ootoovak** [comment]
Hay I just noticed this today https://github.com/SudhagarS/pry-state/commit/e48b2631cf744737fe876f827b5ad99443c0c242 thanks for updating it so quickly. :+1:
