### ISSUE TITLE
Show only ivars

### ISSUE THREAD

**Issue by matrinox** [SudhagarS/pry-state#8]
There are other plugins that show variables inline (e.g. pry-inline) that may be more suited for people. I find this plugin is great at showing hidden state. The variables is nice for those who don't find use in other plugins like pry-inline.

My suggestion is to add an env flag to show only ivars. Another option is to categorize the data. Preliminary list could be:
1. ivars
2. arguments
3. local variables
4. global variables

And then the user can just set the ones they'd like

Again, I can work on this if you want, just let me know what you think about it and the path you want to go down

**Comment by SudhagarS** [comment]
Published gem with changes. Thanks for the contribution mate.
