### ISSUE TITLE
Cant create a class Printer in my project 

### ISSUE THREAD

**Issue by mberrueta** [SudhagarS/pry-state#9]
Hello all

I has issues creating in my project a class `Printer` because the module `/gems/ruby-2.3.2/gems/pry-state-0.1.8/lib/pry-state/printer.rb` already exists.

can be nice if you can add some namespace or module like
```
module PryState
  module Printer
```

nice plugin !!

**Comment by SudhagarS** [comment]
Hello Matias @mberrueta, I should have namespaced a common name like `Printer`. Anyway, thanks for raising the issue. Will push a new version with the changes and notify you.

**Comment by SudhagarS** [comment]
Fixed in new version. Sorry it took so long.
